name:                mp3tag-editor
version:             0.1.0.0
github:              "githubuser/mp3tag-editor"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mp3tag-editor#readme>

dependencies:
- base >= 4.7 && < 5
- gtk3 >= 0.15.8
- directory >= 1.3.8
- bytestring >= 0.11.5
- containers >= 0.6.7
- utf8-light >= 0.4.4
- regex-tdfa >= 1.3.2.2
- encoding >= 0.8.9
- split >= 0.2.5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mp3tag-editor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp3tag-editor

tests:
  mp3tag-editor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp3tag-editor
